import {test,expect} from '@playwright/test';
test('management workflow and responsive layout',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/login');
 await page.getByLabel('Administrator password').fill('browser-test-password');
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Dashboard'})).toBeVisible();
 await page.getByRole('link',{name:'Approvals',exact:true}).click();
 await page.getByRole('link',{name:'Details',exact:true}).click();
 await expect(page.getByRole('heading',{name:'fake-agent'})).toBeVisible();
 await expect(page.getByRole('button',{name:/Reveal Password$/})).toBeDisabled();
 await page.getByRole('button',{name:'Approve',exact:true}).click();
 await page.getByRole('button',{name:'OK',exact:true}).click();
 await expect(page.getByRole('button',{name:/Reveal Password$/})).toBeEnabled();
 await page.getByRole('button',{name:/Reveal Password$/}).click();
 await expect(page.getByRole('button',{name:'Copy Password',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Hide',exact:true}).click();
 await expect(page.getByRole('button',{name:'Copy Password',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'Rotate Password',exact:true}).click();
 await page.getByRole('button',{name:'OK',exact:true}).click();
 await page.getByRole('link',{name:'Settings',exact:true}).click();
 await page.getByLabel('ID Server',{exact:true}).fill('rustdesk.example.com');
 await page.getByLabel('Relay Server',{exact:true}).fill('relay.example.com');
 await page.getByLabel('RustDesk Public Key',{exact:true}).fill('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=');
 await page.getByRole('button',{name:'Save configuration',exact:true}).click();
 await expect(page.getByText('RustDesk OSS server · Policy 2')).toBeVisible();
 await page.getByRole('link',{name:'Dashboard',exact:true}).click();
 await expect(page.locator('.ant-message-notice')).toHaveCount(0, {timeout:10000});
 await page.screenshot({path:'../docs/validation/dashboard.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await expect(page.locator('.ant-layout-sider')).toHaveCSS('width','0px');
 await page.screenshot({path:'../docs/validation/mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 expect(await page.evaluate(()=>localStorage.length+sessionStorage.length)).toBe(0);
 expect(errors).toEqual([]);
});
